version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-test-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventbookings
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

volumes:
  postgres_data_test:
