name: test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Install dependencies
        run: npm i

      - name: Start Docker containers
        run: npm run docker:up

      - name: Wait for server to start
        run: npx wait-on http://localhost:3001/healthcheck

      - name: Run tests
        run: npm t

      - name: Tear down Docker containers
        if: always() # Ensures this step runs even if tests fail
        run: npm run docker:down